name: resscvwebpage
services:
  resscvwebpage:
    public: true
    image: emekaboris/resscvwebpageone:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 2000m
      memory: 5Gi